trigger: 
- main

pool: NEW_POOL

variables:
  KUBECONFIG: 'home/dev-test/kubeconfig.txt' # Specify the correct path to your kubeconfig file
  dockerRegistoryServiceConnection: 'ACR_MSI'
  imageRepository: 'myapplicationdeployments.azurecr.io/maven-app'
  dockerFilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildJar
  displayName: 'Build Jar'
  jobs: 
  - job: BuildJar
    steps: 
    - task: Maven@3
      inputs: 
        mavenPomFile: 'pom.xml'
        goals: 'package'
      displayName: 'build the app'
