trigger: 
- main

pool: NEW_POOL

variables:
  KUBECONFIG: 'home/dev-test/kubeconfig.txt' # Specify the correct path to your kubeconfig file
  dockerRegistoryServiceConnection: 'ACR_MSI'
  imageRepository: 'myapplicationdeployments.azurecr.io/maven-app'
  dockerFilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildJar
  displayName: 'Build Jar'
  jobs: 
  - job: BuildJar
    steps: 
    - task: Maven@4
      inputs:
        azureSubscription: 'MSDN Platforms Subscription(8d350286-edf6-4a53-b8f7-cfcc76ef61e1)'
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
