trigger:
- main

pool: DEV_TEST

variables:
  KUBECONFIG: 'home/dev-test/kubeconfig.txt'
  dockerRegistryServiceConnection: 'ACR_MSI'
  imageRepository: 'myapplication.azurecr.io/mavenapp'
  dockerFilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  KubernetesServiceConnection: 'AKS_MSI'
  namespace: 'maven-app'

stages:

# Build Jar Stage
- stage: BuildJar
  displayName: 'Build Jar'
  jobs: 
  - job: BuildJar
    steps: 
    - task: Maven@4
      inputs:
        azureSubscription: 'MSDN Platforms Subscription(8d350286-edf6-4a53-b8f7-cfcc76ef61e1)'
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
  

# Build Docker Image Stage
- stage: BuildImage
  displayName: 'Build Docker Image'
  jobs:
    - job: BuildImage
      steps:
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce'
        
        # Check if the image already exists in the Azure Container Registry (ACR)
        - task: Docker@2
          displayName: Build and Push Docker Image
          inputs:
            command: buildAndPush
            containerRegistry: $(dockerRegistryServiceConnection)
            Dockerfile: $(dockerFilePath)
            repository: $(imageRepository)
            tags: |
              $(tag)


# Install Trivy Stage
- stage: InstallTrivy
  displayName: 'Install Trivy'
  jobs:
    - job:
      steps:
        - script: |
              echo Installing Trivy...
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/bin
              echo Trivy Installed.
          displayName: Install Trivy
        - script: echo "##vso[task.setvariable variable=TrivyInstalled]true" # Mark Trivy as installed

# Scan Docker Image Stage
- stage: ScanDockerImage
  displayName: 'Scan Docker Image with Trivy'
  condition:  always()  
  jobs: 
    - job: ScanDockerImage
      steps:
        - script: |
              echo Scanning Docker Image...
              imageName=$(imageRepository):$(tag)
              $HOME/bin/trivy image --exit-code 1 --severity HIGH,CRITICAL $imageName
          displayName: Scan Docker Image

# Push Image to ACR Stage
#- stage: PushToACR
  #displayName: 'Push to Azure Container Registry'
  #jobs:
    #- job: PushToACR
      #steps:
        #- task: Docker@2
          #displayName: Push Image to ACR
          #inputs:
            #command: push
            #containerRegistry: $(dockerRegistryServiceConnection)
            #repository: $(imageRepository)
            #tags: |
              #$(tag)

# Deploy to k8s
- stage: DeployImageToKubernetes
  displayName: Kubectl apply 
  jobs:
  - job: 
    steps:
        - script: |
                ls -lR     
        - checkout: self # This will ensure the current repository is pulled
        - task: Kubernetes@1
          displayName: Deploy to kubernetes
          inputs: 
           connectionType: Kubernetes Service Connection
           kubernetesServiceEndpoint: $(KubernetesServiceConnection)
           command: apply
           arguments: -f ./K8/deployment.yaml
           namespace: $(namespace)



